  spring:
    application:
      name: config-server
    profiles:
      active:
        - native
    cloud:
      config:
        server:
          native:
            searchLocations: classpath:/config
            #git:
            # uri: https://github.com/ihuaylupo/config.git
            #searchPaths: licensingservice
  server:
        port: 8071
