  spring:
    application:
      name: config-server
    profiles:
      active:
        - git
    cloud:
      config:
        server:
          native:
            searchLocations: classpath:/config
          git:
            uri: https://github.com/BerkerIgdir/configservice.git
            skip-ssl-validation: true
            search-paths:
              - src/main/resources/config
            basedir: classpath:/config

  server:
        port: 8071
