  spring:
    application:
      name: configserver
    profiles:
      active:
        - git
    cloud:
      config:
        server:
          native:
            searchLocations: classpath:/config
          git:
            uri: https://github.com/BerkerIgdir/configservice.git
            search-paths:
              - src/main/resources/config/{application}
#            TO:DO try to build a fallback mechanism, in case of a connection problem with git
#            basedir: classpath:/config/{application}
            skip-ssl-validation: true

  server:
        port: 8071
